### PR TITLE
fix mobile AOT builds

### PR DESCRIPTION
**Pull request by llwt**
Figured I'd push some of the changes we made to get the AOT build working on our internal fork. 

The build works but for some reason the translations fail to load, not sure why it works internally for us but not here.

Any ideas?

### CODE REVIEW

**Comment by llwt** [comment]
Looks like I was missing `{from: 'assets/i18n/**'},` in the `CopyWebpackPlugin` in the webpack config. Adding that in seemed to fix the translations (I've updated the MR with that change). 

Curious if this looks ok to you now?

**Comment by NathanWalker** [comment]
@llwt Thank you so much! We should compare these changes to this diff:
https://github.com/m-abs/angular2-seed-advanced/tree/fix-bundle-webpack-0.5.0
@m-abs also had this very close.

**Comment by llwt** [comment]
Converted the css files to scss and changed the webpack config to grab the whole assets directory. 

The major place where we differ I think is using `sass-loader` instead of `nativescript-dev-sass`, do you have a preference either way? 

@m-abs, is there a reason you went with `sass-loader` in webpack instead of `nativescript-dev-sass`?

Also, it looks like the `tns-loder.js` was trimmed down but I'm not sure why the rest of it isn't needed any more.

**Comment by m-abs** [comment]
@llwt 
I used the `sass-loader` because of a timing issue and because that's what was used here: https://github.com/sis0k0/nativescript-webpack-sass

The problem was that when `gulp build.prod.tns` does it's job, the app-folder is removed so we start from a clean slate.
So the scss-files weren't compiled.
During a normal "tns run" nativescript-dev-sass compiles the scss files to css and leaves the output in the app-folder, but here I could work out how to trigger that.
Maybe you did?

tns-loader needed to be cleaned up. Most of the code didn't do anything.
It converted templateUrl and styleUrls to require statements, but nativescript-dev-webpack already does this for us.
It tried to use tns.html/css-files, but this was already done by the gulp-tasks.

So all that was really left, was injecting variables.

But I added a workaround for workers, we use in our project.
It is meant to load Workers with 'worker-loader' from triniviz, but I forgot to add that.

But I wasn't finished with the fixes.
I doubt that nativescript livesync works after I switched components to .scss-files... It was needs to be fixed, it was needed for sass-loader to work.

**Comment by llwt** [comment]
Sorry for the delayed response @m-abs, was a busy week.
___
> The problem was that when gulp build.prod.tns does it's job, the app-folder is removed so we start from a clean slate.
So the scss-files weren't compiled.
During a normal "tns run" nativescript-dev-sass compiles the scss files to css and leaves the output in the app-folder, but here I could work out how to trigger that.
Maybe you did?

I was able to trigger the compilation with the `tns prepare <platform>` by adding it before the `build-<platform>-bundle` command:
```
 -    "build.android": "gulp build.prod.tns && cd nativescript && npm run start-android-bundle",
 -    "build.ios": "gulp build.prod.tns && cd nativescript && npm run start-ios-bundle",
 +    "build.android": "gulp build.prod.tns && cd nativescript && tns prepare android && npm run build-android-bundle",
 +    "build.ios": "gulp build.prod.tns && cd nativescript && tns prepare ios && npm run build-ios-bundle",
```
___
>tns-loader needed to be cleaned up. Most of the code didn't do anything.
It converted templateUrl and styleUrls to require statements, but nativescript-dev-webpack already does this for us.
It tried to use tns.html/css-files, but this was already done by the gulp-tasks.

* [ ] Ahh, ok. Sounds like it's safe to pull those changes in.
___
>So all that was really left, was injecting variables.

Does providing the data property also handle template injection into the files? 

I ended up having to add a pipe to the template command in the `build.js.tns.ts` task (did this on our internal fork, not in this MR) to get the env configuration to be properly passed into the mobile app builds (the `JSON.parse('<%= ENV_CONFIG %>');` bit in `src/client/app/modules/core/utils/config.ts`):
```typescript
      const copy = gulp.src(src, {
        base: Config.TNS_APP_SRC,
        cwd: Config.TNS_APP_SRC,
      })
        .pipe(plugins.template(template, {interpolate: /<%=([\s\S]+?)%>/g}))
        // ^^^^^ Added this line
        .pipe(gulp.dest(Config.TNS_APP_DEST));
```
___
> But I added a workaround for workers, we use in our project.
It is meant to load Workers with 'worker-loader' from triniviz, but I forgot to add that.

Triniviz?

___
> But I wasn't finished with the fixes.

__Do you want to combine efforts to get this to a point we can merge into the seed?__

___
>I doubt that nativescript livesync works after I switched components to .scss-files... It was needs to be fixed, it was needed for sass-loader to work.

By using the existing `tns prepare` command the livesync functionality seems to be retained, do you seen any other downsides to using prepare instead of the sass loader?

**Comment by EddyVerbruggen** [comment]
I had webpack build issues (related to css files). This PR works perfectly fine for me, thanks a lot!

**Comment by NathanWalker** [comment]
Thanks for the report @EddyVerbruggen I'm going to merge this - thank you @llwt !!

**Pull request merged**
