### PR TITLE
chore(devDeps): Update dev dependencies

### LINKED ISSUE #41: chore(devDeps): Update dev dependencies
**Major**
- stylelint-config-standard to 5.0.0
  - Removed: font-family-name-quotes, function-url-quotes and string-quotes rules

**Minor**
- tslint to 3.7.1
  - Enhancements & new rules / rule options
- stylelint to 5.3.0
  - Various rule fixes
  - SugarSS & Less syntax support
- colorguard to 1.1.1
  - Upstream dependency updates

**Patch**
- ts-node to 0.7.1
  - Fix for absolute paths
- typings to 0.7.12
  - Improve deprecation and open messages
- chalk to 1.1.3
  - Improve deprecation and open messages

**Associated Fixes**
- Fixed style error in toolbar.component.css ( stylelint update )

### PR DESCRIPTION
**Pull request by joshwiens**
List of updates & reasons in #41 or the commit messages

Includes one style fix post stylelint update

Resolves #41

### CODE REVIEW

**Comment by NathanWalker** [comment]
Thanks @d3viant0ne !  I'll merge this later today. In future, generally dep updates related to built etc. I like to see those updates get merged on the parent angular2-seed first. That way updating to latest upstream parent is a smoother process and avoids duplicate work.

General rule of thumb should be:
- Are these updates going to occur on the parent seed soon?
  - if yes, wait until those changes get merged on parent to then update this with upstream
  - if no, a PR here is good

**Comment by joshwiens** [comment]
@NathanWalker - Same set will land shortly upstream

**Comment by NathanWalker** [comment]
Let's close this PR then and wait til they land upstream and I'll update to latest upstream when they do :+1:

**Comment by joshwiens** [comment]
@NathanWalker - Sorry, I went at all this ass backwards as i'm currently working on Material2 & Ionic2 versions of the advanced seed.

All the devDeps changes have landed in angular2-seed#master

**Comment by NathanWalker** [comment]
N/p... just updated with upstream parent :+1:

**Pull request closed without merging**
