### PR TITLE
Extra routing options

### PR DESCRIPTION
**Pull request by m-abs**
Nativescript-angular have recently added support for page transitions and clear history, this requires the usage of the new class `RouterExtensions`.

This PR adds support for this class in the seed-project by creating a `RouterExtensions` for web that just wraps the `router` and via DI is replaced with the real `RouterExtensions` from `nativescript-angular`.

I've added `pageTransition="slideLeft"` to the navbar link to the `about`-page and added a button on the `home`-component which navigates to the `about`-page with transition=slideTop to show the two ways of using the page transitions.

### CODE REVIEW

**Comment by NathanWalker** [comment]
This is amazing @m-abs really great work! Just looking it over.

**Comment by NathanWalker** [comment]
Can't tell you how much I appreciate this @m-abs 👍  Good stuff.

**Comment by NathanWalker** [comment]
@m-abs after merging and running, looks like the `About` link on the home page just causes browser to refresh and load again?

**Comment by m-abs** [comment]
@NathanWalker 
You're welcome, thanks for merging.

I made a small mistake with the link in the browser. I assumed empty href caused the click to be ignored, I'll create a new pull request to fix it.

**Pull request merged**
