### PR TITLE
Nativescript forms

### PR DESCRIPTION
**Pull request by sanderbos1402**
This fixes the issue that you need to import either the angular forms
module or the nativesciptformsmodule

Exporting it from a platform module outside of the shared app folder
means you can change the implementation.

This should fix issue #365 Error NativeScriptFormsModule import in browser

### CODE REVIEW

**Comment by NathanWalker** [comment]
Hi @sanderbos1402 thanks for the effort and sorry for delay here. I'm unsure about this still, can you provide any simpler option here without introducing another module?

**Comment by sanderbos1402** [comment]
Hi @NathanWalker,
you could of course remove the other parts from the components.module within NS, just keeping the nativescript parts like I did. 
you need to mirror this module on the web like I did in my platforms module

the main module can even be shared by web and NS then.
I did this in another project.
When you need forms etc in NS or Web you import the components.module

I didn't change your structure because there may be a specific reason for this.
This is just to show it works.

Personally I would use a platform module for all platform dependent parts.
and an AppModule which contains the main logic for the application.

I will try to update this pull request later, but I have some deadlines first....

**Comment by NathanWalker** [comment]
No worries thanks, I agree some type of platform module would be nice.

**Comment by NathanWalker** [comment]
@sanderbos1402 Thank you again for this effort - I'm going to close this as will redress later.

**Pull request closed without merging**
