### PR TITLE
feat(Material2): Implement Angular-Material2

### LINKED ISSUE #37: Adding Angular Material v2.0 or Ionic 2.0  to the Advanced Seed
for the past 3 months, I have spent hours, even full whole days doing hard core Mad Science trying to decide between .
-Xamarin - i am a senior .Net developer., my days are full of C#E, besides Xaml comes naturally
-Apache Cordova , with 3 years with Angular and built 3 enterprise apps, i now love my JavaScript and angular coding ... love it so much , so i wanted to hybrid with Cordova. unfortunately plug-in are a pain to work with and specially maintain consistency , besides Hybrid are not Native..
-React Native , well everybody was telling me to go this route 

but none of the above 3 convinced me  or my team.  
until I saw the angular 2 advanced seed. by far the best contribution someone can do for all developers,

By creating this template you have truly opened the doors and designed a true path towards Angular 2.0 as well as started a revolution on how software applications will be from now on.  

In my humble opinion , i think you will make it perfect  by adding Ionic 2 or Angular Material 2 to the mix.
is that on you radar ?

### PR DESCRIPTION
**Pull request by joshwiens**
- [x] angular-material2 systemjs configuration
- [x] Karma config updates for material2
- [x] Materialize `Home Component`
- [x] Materialize `About Component`
- [x] Materialize `Toolbar Component`
- [x] Materialize `Navbar Component`
- [x] Enable Material2 Production Build
- [ ] Fix e2e tests
- [ ] Wiki Documentation

**Current Limitations**
- Bug in `md-input` when used in `"@angular/forms": "0.1.1"`
- No styling using default theme for `md-button` on hover

Resolves #37

### CODE REVIEW

**Comment by NathanWalker** [comment]
@d3viant0ne just pushed up some refactorings... shouldn't affect your changes here, but when you get a chance, go ahead and merge in latest master here 👍

**Comment by joshwiens** [comment]
Will do, still have the e2e tests to rewrite & one weird bug with forms / md-input to try and run down.

**Comment by divramod** [comment]
hey you two, are there any estimations when this will be usable?
how can i start to test it now? or can i help in any way?

**Comment by joshwiens** [comment]
@divramod - Even when it's usable, it's not really "usable" until Material2 hits what I can only assume late beta ( where Jeremy Elbourn is planning on having feature parity with material 1.x)

From personal experience, to currently build a full material site of any substance you need both angular-material2 & ng2-material and probably a few custom components to fill in the gaps and even with all that, you can't change the colors of any of the components.

There is no theming support, testing is sketchy and the sheer number of libs needed for visual components makes the whole thing bulky. I've left this where it is precisely because Material2 simply isn't ready yet ( nor should it be expected to be ) and will lead to more questions / issues than value. I've opened the PR for anyone that wants to tinker around with Material2.

If it exists, people will try and build with it and having rode the bleeding edge from the first alpha build this really should not land until the beta time frame. That said, if you want to beat your head against Material2, all you have to do is look at what has already been added in this PR as the only thing missing at the moment is the re-writing of all the e2e tests which is ~30 minutes of work.

I leave the decision to @NathanWalker but my honest opinion is landing this in it's current state, given people have been building real applications with the seed / advanced seed since early Angular beta is going to be doing us and the consumers of the advanced-seed a disservice.

**Comment by NathanWalker** [comment]
Since this would just be merged to `material2` branch only, I'm ok with merging this whenever and continuing development of material integration on that branch. 👍

**Comment by divramod** [comment]
@d3viant0ne thx for your detailed explanation. this all makes sense.
@NathanWalker it would be nice to see this pull request merged even if its not completely ready

can you both give me a tip which ui framework i should use to start a project with the advanced seed.?

**Comment by joshwiens** [comment]
@divramod - The most robust right now is going to be ng2-bootstrap assuming you want native angular2 components. I'm not sure about it's stability.

 The very simple truth is there is no good answer right now.

**Comment by divramod** [comment]
@d3viant0ne thx for the info! i will give ng2-bootstrap a try

**Comment by joshwiens** [comment]
@divramod - I completely forgot about another completely viable option that would keep you in the material design realm.

https://github.com/dogfalo/materialize/

along with ...

https://github.com/InfomediaLtd/angular2-materialize

It would at the very least, fill the gaps until angular-material2 is full featured and stable.

**Comment by divramod** [comment]
@d3viant0ne thx for the hint. i defenitely prefer material over boostrap and will go the material way if possible. your recommended approach will also make it easier to migrate to material2.

do you have some experiences regarding https://github.com/dogfalo/materialize/ and https://github.com/InfomediaLtd/angular2-materialize used with nativescript?

i try to use as less as possible libs/frameworks in my project and would really like to be able to use the same ui framework everywhere (browser, ns, electron).

**Comment by joshwiens** [comment]
@divramod - I'll be playing with it this weekend as I am in the same boat you are... Need material like yesterday and the options are limited. You can find me in the {N} slack channel.

As to NativeScript specifically, I can't think of a reason why the two libs can't live together.

I'll be finishing this PR in the morning & then making a materialize branch ( like this one ) and we will see how everything works.

**Comment by divramod** [comment]
@d3viant0ne nice. i really appreciate your work here and looking forward to the materialize branch. i am not that deep into typescript/ng2/systemjs and the advanced-seed but i hope i can help you in some way to get everything running.

**Pull request closed without merging**
