### PR TITLE
Chore - Update ng2-translate dependency to v2.2.2 

### PR DESCRIPTION
**Pull request by lfarran**
Update ng2-translate dependency to v2.2.2 for Angular2 RC3

### CODE REVIEW

**Comment by NathanWalker** [comment]
@lfarran I believe there's an issue with latest 2.2.2: https://github.com/ocombe/ng2-translate/issues/61#issuecomment-228141939

**Comment by amirtoole** [comment]
Language switch issues are delaying #133 from being finished. I documented a really hacky way of resolving the language change issue in https://github.com/NathanWalker/angular2-seed-advanced/commit/dd71513e38fff7f4f184332213777524298c0eff#commitcomment-18017890
Call `translate.use(lang)` twice per language switch.

**Comment by NathanWalker** [comment]
I'll have a look at 2.2.2 this week and try to figure out what's going on.

**Comment by NathanWalker** [comment]
This is on master now... dep update came along with several others.

**Comment by NathanWalker** [comment]
The 2.2.2 ng2-translate does still experience the initial switch issue where no change detection is fired. After navigating route it fires CD and view is updated with language change. Will investigate with ng2-translate itself. Since that issue was also experienced with 2.1, I went ahead and updated to 2.2.2.

**Comment by friksa** [comment]
this worked for me in in multilingual.service.ts constructor:

```
    store.select('i18n').subscribe((state: MultilingualStateI) => {
      // update ng2-translate which will cause translations to occur wherever the TranslatePipe is used in the view
      if (this.translate.getLangs() && (this.translate.getLangs().indexOf(state.lang) > -1)) {
        this.translate.use(state.lang);
      } else {
        this.translate.reloadLang(state.lang).take(1).subscribe(() => {
          setTimeout(() => this.translate.use(state.lang), 0);
        });
      }
    });
```

Credit to:
http://stackoverflow.com/questions/38272388/ng2-translate-translation-strings-not-updating-in-components-with-onpush-chang

**Comment by NathanWalker** [comment]
Thank you @friksa just pushed your workaround to master. Solid way to handle for now. 👍

**Comment by lynsei** [comment]
just an FYI... this code:

```
store.select('i18n').subscribe((state: MultilingualStateI) => {
  // update ng2-translate which will cause translations to occur wherever the TranslatePipe is used in the view
  if (this.translate.getLangs() && (this.translate.getLangs().indexOf(state.lang) > -1)) {
    this.translate.use(state.lang);
  } else {
    this.translate.reloadLang(state.lang).take(1).subscribe(() => {
      setTimeout(() => this.translate.use(state.lang), 0);
    });
  }
});
```

... fails when compiling via node 5.12.0 x64 and emulating via your gulp task for "start android / start.livesync.android"

I'm researching how this might be fixed.  It doesn't appear to like the rxjs take method... not sure yet if that's being caused by the language files not being copied to the device properly, or whether it's some problem with the usage of the method itself.

**Pull request closed without merging**
