### PR TITLE
Fixing protractor test extension in configuration file

### PR DESCRIPTION
**Pull request by JakePartusch**
Looks like in the master seed the e2e test files were renamed, but the files in this seed still match the old pattern. This PR changes the protractor conf file back so it will pick up the tests.

### CODE REVIEW

**Comment by pidupuis** [comment]
Your modification is the exact revert of the following recent _fix_: https://github.com/NathanWalker/angular2-seed-advanced/commit/6a9dd2fda675807ebc0748e4d2c2cdbe76628b28

**Comment by JakePartusch** [comment]
Very true! I believe that commit was pulled in from the parent seed. In the parent seed, they recently renamed all of the *.e2e.ts files to *.e2e-spec.ts. In this seed, they are still *.e2e.ts.

**Comment by pidupuis** [comment]
Good guess, but there are several remaining `e2e-spec` in the code. Maybe this PR could fix this too :wink:

**Comment by NathanWalker** [comment]
Hi @JakePartusch thanks for this, but yes we want to be in sync with parent seed all the time so since it was recently updated to `e2e-spec` we should update these here. Not sure how that change got lost in a recent upstream merge. But if you want to update all e2e files here to use `e2e-spec` and keep protractor conf the way it was, then I can merge this. Thanks!

**Comment by NathanWalker** [comment]
Awesome thanks!

**Pull request merged**
