### PR TITLE
symlink error check

### PR DESCRIPTION
**Pull request by Kaffiend**
On Windows the `docker-compose build` would fail and try to run `sudo` to create the link when it already exists on a windows machine.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Thank you @Kaffiend ! Is this good to go at this point or does anything else need to be done?

**Comment by Kaffiend** [comment]
No problem @NathanWalker Yessir, It fixed the docker build on both my windows machines, and my Linux box appears to be unaffected as well.

**Comment by Kaffiend** [comment]
I'm still concerned as to why this section of [install.js](https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/install.js#L73) did not catch on the process platform and re-symlink with the correct OS command. 
when i run `node -p process.plaform i get the expected 'win32' return. I also tried adding the dedicated `os` module and using `os.platform()` which returns the same thing and it still tries to use `sudo` perhaps someone more familiar can spot why its doing that. That is what the underlying cause is. What i added I would only consider a work around TBH.

**Comment by Kaffiend** [comment]
```
Configuring...
Attempting to Symlink ../src/client/app ../nativescript/src/app/
Symlink error:  { Error: EEXIST: file already exists, symlink '/home/app/angular-seed/src/client/app' -> '/home/app/angular-seed/nativescript/src/app'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at createSymLink (/home/app/angular-seed/tools/install.js:110:8)
    at Object.<anonymous> (/home/app/angular-seed/tools/install.js:41:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: '/home/app/angular-seed/src/client/app',
  dest: '/home/app/angular-seed/nativescript/src/app' }
linux  <----process.platform logged out with error
```
Ok so this is from within the docker container which is linux. This tells me that the issue is sudo is not included with the container distro. And what i added fixed my issues because the link is already there and we were only looking for any error in general to recreate the link. So if we want to always recreate the link we need to make sure sudo is included in the distro the container is running.

edit - this will prevent it from recreating the link if its already there, as sudo. but sudo not being included in the container distro is another issue.

**Comment by Kaffiend** [comment]
added a message to appear after the "Attempting to create a symlink.." message, if the link already exists. This is as far as i go on this issue though. adding sudo to the container distro is more than I can get into right now, I'm not entirely sure its even needed. But this PR is good to go for fixing the `docker-compose build`

**Comment by NathanWalker** [comment]
Excellent thank you 👍

**Pull request merged**
