### PR TITLE
NativeScript 3.0, Angular 4.1, TypeScript 2.2

### PR DESCRIPTION
**Pull request by NathanWalker**
* Also merges in latest from upstream parent seed

Almost there - issue with `build.js.tns.ts` (related to gulp-template):

```
ReferenceError: args is not defined
    at eval (lodash.templateSources[9]:11:10)
    at DestroyableTransform._transform (/Users/nathan/Documents/github/NathanWalker/angular-seed-advanced/node_modules/gulp-template/index.js:22:40)
    at DestroyableTransform.Transform._read (/Users/nathan/Documents/github/NathanWalker/angular-seed-advanced/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/nathan/Documents/github/NathanWalker/angular-seed-advanced/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/nathan/Documents/github/NathanWalker/angular-seed-advanced/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/Users/nathan/Documents/github/NathanWalker/angular-seed-advanced/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at DestroyableTransform.Writable.write (/Users/nathan/Documents/github/NathanWalker/angular-seed-advanced/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:264:11)
    at DestroyableTransform.ondata (/Users/nathan/Documents/github/NathanWalker/angular-seed-advanced/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:541:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
```

### CODE REVIEW

**Comment by amirtoole** [comment]
Hey @NathanWalker 
I dug a bit into this to see what was going wrong. The two files that are causing gulp-template to throw errors are:

1. nativescript/src/mobile/core/services/ns-app.service.ts
```TNS_CONFIG.ANALYTICS_TRACKING_ID``` is not being properly converted.

and

2. src/app/shared/i18n/services/i18n.providers.ts
(entirely commented out)
(not sure why this is causing an error)

Will PR in a bit if you don't beat me to it.

**Comment by KANekT** [comment]
You planned Use routing corresponding to STYLE 02-12?

https://raw.githubusercontent.com/mgechev/angular-seed/master/src/client/app/app-routing.module.ts

**Comment by NathanWalker** [comment]
@KANekT hi - yes I do plan to implement an example lazy loading module with child routes which works across web and mobile here soon.

@hellofornow the gulp-template error is interesting as it has never occurred before and on the surface appears to suggest some api change with gulp-template however this PR presents no updates to that dependency so it may be something else related to a config file change coming from upstream parent seed changes. Trying to circle back here to investigate more. Lemme know if you find anything else out here. This PR is so close, just held up by that 1 obscure issue.

**Comment by NathanWalker** [comment]
Disabled template variable handling in `ns-app.service` for time being - it was minor what that was handling anyway. May circle back in future.

Additionally `SegmentedBar` is commented our for {N} template of lang-switcher.component, reporting a potential 3.0 issue for that - but for now the `SegmentedBar` is commented out of this template:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/app/shared/i18n/components/lang-switcher.component.tns.html

**Comment by NathanWalker** [comment]
LangSwitcher works well now and exemplifies how one could create custom view helpers that are platform specific (related to new {N} 3.0 changes to `SegmentedBar`):
https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/app/modules/i18n/components/lang-switcher.component.ts#L58-L61
Then the {N} app can simply provide the appropriate view helper:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/nativescript/src/native.module.ts#L84

**Pull request merged**
