### PR TITLE
Update start.desktop command

### PR DESCRIPTION
**Pull request by jvitor83**
Fix for a new line command

### CODE REVIEW

**Comment by NathanWalker** [comment]
@jvitor83 Thanks for the contributions. Unfortunately this change doesn't work for me.
Is this for a specific platform, Mac or Windows?

With this change on Mac at least, the environment is always `production` but instead that npm script should keep the environment set to `development`.

**Comment by jvitor83** [comment]
My change is because the script doesn't work on windows.
I take a look at the script and think it has missed the &&. Then i put it and has started to work on windows.
Maybe it need to be cross-platform?!?

**Comment by jvitor83** [comment]
Make some changes to create a script command (npm run) to start electron on windows.

**Comment by NathanWalker** [comment]
@jvitor83 Ok was able to verify this fix does work for Windows. Thanks for adding as a separate npm script.

If you don't mind, please squash into 1 commit and I can merge this today, thanks again!

Btw, when I ran in Virtual Box on my Mac (Win 8.1/IE 11), I see the following, do you?
It's like the background-color is not getting set to white. Not sure if this is just my Virtual Box setup or not.
If you see that as well and know a fix (must be Windows only as Mac does not experience this), please let me know.
screen shot 2016-03-31 at 9 23 53 am

**Comment by jvitor83** [comment]
Ok, i make a new PR ( https://github.com/NathanWalker/angular2-seed-advanced/pull/31 ).

About the glitch, i have this issue too on windows. 
It seems the css are not been loaded. Will try to take a look on this.

**Comment by NathanWalker** [comment]
I'm a Mac user so unfortunately not 100% certain on some of the edge cases on Windows.
If you can help contribute on that regard would be really great. :+1:

**Comment by NathanWalker** [comment]
@jvitor83 It's worth noting that when building the release for electron using `npm run build.desktop.windows` works well (no css issue).

So definitely isolated to development only issue.

**Pull request closed without merging**
