### PR TITLE
Rc.6

### PR DESCRIPTION
**Pull request by NathanWalker**

### CODE REVIEW

**Comment by NathanWalker** [comment]
Web all clear. Awaiting rc.6 compatibility with [nativescript-angular](https://github.com/NativeScript/nativescript-angular)

**Comment by NathanWalker** [comment]
https://github.com/NativeScript/nativescript-angular/issues/429

**Comment by mko** [comment]
bitmoji

**Comment by NathanWalker** [comment]
Updated to latest upstream parent: https://github.com/mgechev/angular2-seed
Lots of good stuff here.
Still awaiting `nativescript-angular` (looks like they are getting there): https://github.com/NativeScript/nativescript-angular/pull/440

**Comment by vincentpalita** [comment]
Hi @NathanWalker thank you for all this awesome great work!!

Since the last merge with parent seed, there is an issue in the src/client/main.web.prod.ts file, it's looking for the web.module.ngfactory which does not exist.

I don't really know at this time what you are willing to do with that part of the seed.

**Comment by NathanWalker** [comment]
@vincentpalita `web.module.ngfactory` is auto-generated when you run `npm run build.prod.exp` with the changes on this branch. 👍

**Comment by vincentpalita** [comment]
Hello @NathanWalker! Thank you for your reply.
I had a different build.prod.ts file in my project folder and the build was failing. Deleting it and using the seed one's make it work again :)

**Comment by NathanWalker** [comment]
rc.6 just landed in `nativescript-angular`... I will try to integrate and get this PR merge later today.

**Pull request merged**
