### PR TITLE
Angular 4 + {N}ng 1.5.0 + latest parent seed

### PR DESCRIPTION
**Pull request by NathanWalker**

### CODE REVIEW

**Comment by NathanWalker** [comment]
@yavin5 When you get a chance, would you be so kind to pull this branch (clear node_modules, etc and reinstall clean) and try to run `npm start`.  The dev web server opens to a blank page - after investigation it appears to be related to some of your recent dev server changes that I couldn't track down. :(

Everything else works, build.prod, serve.prod, test, {N} app, even desktop electron app 👍 
But yeah just the `npm start` dev web server with browser-sync has something missing.

**Comment by yavin5** [comment]
Ooh, Angular 4!  Okay, I will try this soon, and see what I can see, and
I'll reply back.

Thanks.

Yavin Five

**Comment by hellofornow** [comment]
Found a fix for the dev web server; not sure if it's the *best* solution, but is working for both web and desktop. #394

**Comment by amirtoole** [comment]
Okay; attempt 2 for this fix #395 
The way the parent seed serves dev vs production means we need to be careful when setting APP_BASE to '/' vs ''.

When using electron or when serving production code we want APP_BASE to be ''.

However in web dev mode browser sync is used (vs express) and needs to be prefixed with '/'.

~~I also removed some redundant code in seed/server.ts. Not sure if others noticed, but I would frequently see browser reload being fired multiple times; not sure if this was the culprit, but I've made this line up with parent seed.~~

**Comment by NathanWalker** [comment]
@hellofornow 👍 👏 👏   - looks like `npm test` has issue - looking now

**Comment by yavin5** [comment]
Is there still a problem with npm start, or is that now fixed?  The changes to the server classes don't appear to make a functional change that could fix something.

**Comment by NathanWalker** [comment]
There is not - fixes were related to base URL path needing to be different for dev. Nothing functional - master is fully operational.

**Pull request merged**
