### PR TITLE
Adding SASS CSS preprocessor 

### PR DESCRIPTION
**Pull request by lfarran**
Adding SASS CSS preprocessor via gulp-sass and gulp-autoprefixer
Adding SASS linter with gulp-scss-lint
Updated README.md for required scss_lint Gem dependency for
gulp-sass-lint
Switched project’s CSS to SASS files and addressed SASS linting errors
Update performed with Node v5.10.1 and npm v3.8.3

### CODE REVIEW

**Comment by lfarran** [comment]
Also ran with Node v5.11.1 and npm v3.8.6.

**Comment by NathanWalker** [comment]
This is awesome @lfarran  thank you!
@d3viant0ne Have any thoughts here? (review?)

**Comment by NathanWalker** [comment]
@lfarran Only thing I'll mention is there's a side of me that opts for `LESS` over `SASS` due to fact this brings another dependency on another language, ruby, whereas, `LESS` is just js.

**Comment by lfarran** [comment]
The reason I chose SASS over LESS was that Bootstrap and Angular Material are both using SASS.  The gulp-sass dependency uses node-sass which doesn't use Ruby.  If Ruby is the concern, removing gulp-scss-lint could fix that.  However, I see value in the SASS linter.

**Comment by NathanWalker** [comment]
Definitely @lfarran I really like this, lemme see if @d3viant0ne has any comments before merging.

**Comment by NathanWalker** [comment]
@lfarran can you ensure that your `SASS` setup here also works with the {N} app?
I believe this would be the thing to use: https://github.com/toddanglin/nativescript-dev-sass

**Comment by lfarran** [comment]
@NathanWalker The SASS setup works for the {N} app with https://github.com/toddanglin/nativescript-dev-sass. To install: cd nativescript, tns install sass.  Is there a good way to script this automatically install, or is it sufficient to add an install note in the README under the NativeScript section?  I'm also debating how the SASS linting should work for the {N} app, combine with the current gulp scss-lint task or make separate?

**Comment by NathanWalker** [comment]
You should be able to:

```
cd nativescript
npm i nativescript-dev-sass --save
```

To ensure it's saved to the {N} app's dependencies, then all should be good to go.
SASS linting I'm unsure of, but it'd be okay to leave linting out of the {N} app for now since some debate around build integrations is still circling.

**Comment by joshwiens** [comment]
@NathanWalker My only comment is the same I always make, it limits what others can use which is why I lean towards examples as opposed to sticking framework X into something that is supposed to be generic.

I use scss in most of my projects but it's not included in my boilerplate for client projects at work. sass isn't always the right answer so I prefer to be able to support it without implementing something specific.

The end result of this could be after this merges that you end up with a bunch of less / postcss users that have to rip all this out every upstream update to use their prefered CSS pre / post processor.

**Comment by NathanWalker** [comment]
@d3viant0ne thank you for that 👍 
@lfarran I do agree with Josh's comments, what do you think if we merged this to a branch called `sass` and document it as an option in the `readme`?

**Comment by joshwiens** [comment]
@NathanWalker That's something I've tried to get into seed upstream. We need to support common integrations better and forks are deficient in that regard.

Incoming pull requests could be vetted against integration branches to find problems before they make master and cause users pain when updating.

So you could do one for SASS, on for Material2 & perhaps one for ng2-bootstrap which should in theory enable us to find issues in PRs or refactoring before they make master.

PRs are opened to develop and merged in, then rebased into the integration branches off of develop. If everything checks out, it's merged down into master with reasonable confidence that people can pick up that change set without breaking projects built on top of the advanced seed.

**Comment by joshwiens** [comment]
And if you opt to go that direction, create a branch for Material2 and i'll get to work on it.

**Comment by NathanWalker** [comment]
Material2 branch:
https://github.com/NathanWalker/angular2-seed-advanced/tree/material2
Sass branch:
https://github.com/NathanWalker/angular2-seed-advanced/tree/sass
ng2-bootstrap:
https://github.com/NathanWalker/angular2-seed-advanced/tree/ng2-bootstrap

👍

**Comment by NathanWalker** [comment]
@lfarran Once you have this comment addressed:
https://github.com/NathanWalker/angular2-seed-advanced/pull/77#issuecomment-219940263
Just close this PR and reopen to target the `sass` branch and I'll get it merged. Thank you very much for your efforts!

**Comment by chriswep** [comment]
I like the concept with the branches. 

What would the workflow be if - lets say - i want to use the advanced-seed with sass und material? Would i merge all three branches (master, sass, material) into my local branch on every update? Couldn't this get messy with the time?

**Comment by joshwiens** [comment]
@metzc - The integration branches are more to aid us in validating changes against common integrations and finding issues with code changes before they land in master and effect users with projects built on top of the advanced-seed.

IMO in a production product, you may or may not fork the advanced-seed directly. Either way, I would suggest only pulling updated form upstream master to <yourFork> master.

No framework integration is going to meet everyones requirements exactly, these integration branches exist as a guide to users and to simplify validation for maintainers to prevent changes from landing in master that break common integrations. Nobody is suggesting that people build on top of integration branches.

**Comment by JakePartusch** [comment]
Maybe this is a little overreaching, but would this project be better served as a generator? So that users would be able to pick and choose the technologies that they want to integrate. I know this brings in another set of issues, but it might be better than maintaining a bunch of branches.

**Comment by joshwiens** [comment]
@JakePartusch - That idea was already proposed and started by @ludohenin. With offline comp & the cli coming, creating a generator is a lot of work with very little payout at the moment.

The only people that "have" to manage branches are the project maintainers and that is specifically to find problems before they hit master. A generator doesn't help solve that problem.

**Comment by JakePartusch** [comment]
@d3viant0ne thanks for the info! I didn't know that @ludohenin was working on something similar. Even so, the same argument that is being made for/against sass could be made for/against any other proposed technology addition. How is it decided what gets integrated vs. put in a branch?

Also, this might be relevant to this conversation: https://github.com/mgechev/angular2-seed/issues/746

**Comment by joshwiens** [comment]
IMO the general rule would be technologies what have popular alternatives.

i.e. 
Pre/PostCSS vs. SASS vs. Less
Material2 vs. Bootstrap vs. polymer

We have broken common technology integrations in the seed quite a few times and finding out after the fact that a change we made had adverse effects on someone real world projects is the suck.

Running branches for integrations may or may not help but something needs to be done to give people more confidence in stability when pulling changes into their forks.

**Comment by lfarran** [comment]
@NathanWalker Sorry for the delay. I have addressed the comments in #77 (comment), merged the changes to the sass branch, and created PR 82.  I'm closing this PR per your request.

**Pull request closed without merging**
